### ISSUE TITLE
Update to new format

### ISSUE THREAD

**Issue by lauraclay** [raspberrypilearning/sonic-pi-competition-2014#5]
- [ ] cover.png
- [x] LICENCE.md
- [x] CONTRIBUTING.md
- [x] meta.yml
- [ ] hardware.yml
- [ ] software.yml
- [ ] extras.yml
- [x] overview.md
- [x] learn.md
- [ ] lesson.md
- [ ] ks.md

**Comment by lauraclay** [comment]
lesson.md files need moved into lesson folders.

**Comment by lawsie** [comment]
Closing this issue as this resource is 3 years old
